# Generated by Django 3.2.6 on 2021-08-15 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db import transaction
import datetime
from django.contrib.auth.models import User

def insert_data(apps, schema_editor):

    daftar_dapil = [
        [1, 'UNAS PASIM'],
        [2, 'Asbar'],
        [3, 'Asri'],
    ]

    daftar_angkatan = [
        [16, 'Malware'],
        [17, 'Firewall'],
        [18, 'Jarvis'],
        [19, 'Neophyte'],
    ]

    daftar_anggota = [
        ["0402067001", "Abdul Hafiz Tanjung", 1, None, 10],
        ["0429056401", "Rinalwan Buchari", 1, None, 10],

        ["0203171082", "Fitriani", 2, 16, 1],
        ["0102171037", "Helma Yunia Putri", 3, 16, 1],
        ["0203171083", "Herdiana", 1, 16, 1],
        ["0101171134", "Lusi Kusnaeni", 2, 16, 1],
        ["0203171084", "Nenti Gustini Nurhidayah", 2, 16, 1],
        ["0406171007", "Putria Nur'ainun", 2, 16, 1],
        ["0203171085", "Rizky Fardiansyah Tanjung", 1, 16, 1],
        ["0102171047", "Salma Rizkiyanti Alamsyah", 3, 16, 1],
        ["0203171086", "Sinta Cantika", 2, 16, 1],
        ["0101171156", "Siti Salbyah", 2, 16, 1],
        ["0305171046", "Tiara Guntari", 3, 16, 1],
        ["0203171087", "Wia Handayani", 2, 16, 1],
        ["0203181027", "Ade Radia Rahmat", 1, 17, 1],
        ["0305181058", "Anjani Arum Safitri", 3, 17, 1],
        ["0102181021", "Annisa Rizky Mulya", 2, 17, 1],
        ["0204181015", "Dio Prasetiyo", 1, 17, 1],
        ["0406181006", "Hesti Lestari", 3, 17, 1],
        ["0102181024", "Ica Octa Monica", 2, 17, 1],
        ["0101181139", "Kartini Rosady Tanjung", 3, 17, 1],
        ["0203181044", "Randi Firmansyah", 1, 17, 1],
        ["0102181023", "Sri Putri Andriani", 2, 17, 1],

        ["02041911001", "Ade Heriyanto", 1, 18, 1],
        ["03051911024", "Adi Kurniawan", 1, 18, 1],
        ["01021911017", "Af'idatul Maghfiroh", 2, 18, 1],
        ["02041911002", "Anjar Maulana", 1, 18, 1],
        ["02041911003", "Annisa Nur Wachidah", 2, 18, 1],
        ["02041911005", "Arina Anggelina Lubis", 3, 18, 1],
        ["02041911006", "Auliya Annidatunnisa", 2, 18, 1],
        ["02041911007", "Candra Komara", 1, 18, 1],
        ["02041911008", "Dede Rifaldi", 1, 18, 1],
        ["01021911021", "Dian Nurul Khazaainatu Qurrota A'yun", 3, 18, 1],
        ["02041911009", "Diki Indrayana", 1, 18, 1],
        ["02041911011", "Eka Apriliani", 2, 18, 1],
        ["01021911024", "Elvina Fitriani", 2, 18, 1],
        ["02041911012", "Fatin Firdiansyah", 1, 18, 1],
        ["03051911029", "Galih Ahmad Septian", 1, 18, 1],
        ["02031911056", "Habib Jannata", 1, 18, 1],
        ["02031911057", "Hanafi Abdullah", 1, 18, 1],
        ["02041911013", "Hani Octaviani", 2, 18, 1],
        ["02041911014", "Hasby Ramadhan", 1, 18, 1],
        ["02041911015", "Helen Miftakhul Jannah", 3, 18, 1],
        ["02041911016", "Hera Elvira", 3, 18, 1],
        ["02041911017", "Ima Nirmala", 2, 18, 1],
        ["02041911018", "Iqbal Sihabudin", 1, 18, 1],
        ["02041911019", "Iskandar Zulkarnain Hasibuan", 1, 18, 1],
        ["02041911020", "Jaja Nurjana", 1, 18, 1],
        ["02041911021", "Lulu Fitri Ramadani", 3, 18, 1],
        ["02041911022", "Mar'atus Sholikha", 2, 18, 1],
        ["02041911023", "Mia Salha Syakila", 2, 18, 1],
        ["03051911032", "Moh Afkarul Haq", 1, 18, 1],
        ["02041911024", "Muhammad Rizal", 1, 18, 1],
        ["02041911025", "Nikita Putri Septemby", 3, 18, 1],
        ["02041911026", "Putri Melenia", 2, 18, 1],
        ["02041911027", "Rahma Danil", 1, 18, 1],
        ["02041911028", "Rahma Fauziah", 2, 18, 1],
        ["02041911029", "Raisa Kamel", 2, 18, 1],
        ["02031911067", "Romi Kusuma Bakti", 1, 18, 1],
        ["02041911030", "Siti Nuraisah", 3, 18, 1],
        ["02041911031", "Siti Nursabila", 2, 18, 1],
        ["02041911032", "Tasya Nurfatimah", 3, 18, 1],
        ["01021911037", "Tiara Agustin", 2, 18, 1],
        ["02031911070", "Titik Andini", 2, 18, 1],
        ["02041911033", "Tito Soediro", 1, 18, 1],
        ["03051911040", "Yoga Hendrapratama", 1, 18, 1],
        
        ["02042011001", "Agus Shofyan Dwi Saputro", 1, 19, 1],
        ["02042011002", "Aren Kurnia", 3, 19, 1],
        ["02042011003", "Ari Sandi Shefa Maldini", 1, 19, 1],
        ["02042011004", "Arie Akbar", 1, 19, 1],
        ["02042011005", "Aris Purnama", 1, 19, 1],
        ["02042011006", "Asep Hidayat", 1, 19, 1],
        ["02042011007", "Awaludin Muhammad Iqbal", 1, 19, 1],
        ["02042011008", "Bayu Wijiana", 1, 19, 1],
        ["02042011009", "Burhanudin Hawari", 1, 19, 1],
        ["02042011010", "Cahaya Hartati Sitanggang", 3, 19, 1],
        ["02042011011", "Dani Hidayat", 1, 19, 1],
        ["02042011012", "Dion Ferdian Syam", 1, 19, 1],
        ["02042011013", "Edwar Maulana Sitompul", 1, 19, 1],
        ["02042011014", "Imron Fuadi", 1, 19, 1],
        ["02042011015", "Indah Mentari", 3, 19, 1],
        ["02042011016", "Jamil Hamdi Harahap", 1, 19, 1],
        ["02042011017", "Kurnia Zulianti", 3, 19, 1],
        ["02042011018", "Mita Zuriati", 3, 19, 1],
        ["02042011019", "Muhammad Rozin Dzakwan", 1, 19, 1],
        ["02042011020", "Muzayyin Al-Afnan Siregar", 1, 19, 1],
        ["02042011021", "Nushrotummillah Nurul 'Aini", 3, 19, 1],
        ["02042011022", "Risa Alfadila", 3, 19, 1],
        ["02042011023", "Sabila Noor Sania", 3, 19, 1],
        ["02042011024", "Seli Deslia", 3, 19, 1],
        ["02042011025", "Sely Amalia", 3, 19, 1],
        ["02042011026", "Sri Nuhayatun", 3, 19, 1],
        ["02042011027", "Yusfa Julian", 1, 19, 1],
    ]

    daftar_jadwal = [
        [datetime.date(2021, 7, 31), None, 'Pembentukan Panitia Pemilu PUB (KPU PUB)'],
        [datetime.date(2021, 8, 1), None, 'Pengumuman nama dan nomor urut calon ketua/keamanan'],
        [datetime.date(2021, 8, 13), datetime.date(2021, 8, 15), 'Kampanye'],
        [datetime.date(2021, 8, 15), datetime.date(2021, 8, 16), 'Pendaftaran anggota'],
        [datetime.date(2021, 8, 16), None, 'Masa tenang'],
        [datetime.date(2021, 8, 17), None, 'Pemungutan dan penghitungan suara'],
        [datetime.date(2021, 8, 24), None, 'Penetapan ketua dan keamanan'],
        [datetime.date(2021, 10, 1), None, 'Pelantikan ketua dan keamanan terpilih'],
    ]

    daftar_kandidat = [
        [1, False, '03051911032', '1.png', 'blue',
            'Bersama-sama dengan pembina dalam mewujudkan anggota-mahasiswi program beasiswa PUB yang unggul baik secara agama, hard skill, maupun soft skill.'],
        [2, False, '02031911056', '2.png', 'red',
            'Mewujudkan terselenggaranya program PUB menjadi lebih baik lagi.'],
        [3, True, '02042011005', '3.png', 'orange', None],
        [4, True, '02042011012', '4.png', 'deepPurple', None],
        [5, True, '02042011027', '5.png', 'green', None],
    ]

    daftar_misi = [
        [1, 'Meningkatkan kedisiplinan dalam hal beribadah kepada Allah SWT.'],
        [1, 'Mengevaluasi serta meningkatkan peran dan fungsi dari setiap divisi sehingga lebih optimal dalam bidangnya masing-masing.'],
        [1, 'Meningkatkan rasa memiliki baik terhadap program PUB maupun antarsesama anggota-mahasiswi PUB.'],
        [1, 'Membina suasana kehidupan yang mandiri, teratur, dan sesuai dengan peraturan yang berlaku.'],

        [2, 'Meningkatkan nilai-nilai keimanan dan ketakwaan kepada Allah SWT.'],
        [2, 'Mengoptimalkan keselarasan kinerja pengurus dan seluruh anggota-mahasiswi PUB.'],
        [2, 'Mempererat tali silaturahmi dan kekeluargaan baik dengan sesama anggota-mahasiswi PUB, pembina PUB, maupun seluruh masyarakat di Universitas Nasional PASIM.'],
        [2, 'Meningkatkan kegiatan yang menunjang soft skill baik akademik maupun nonakademik.'],
        [2, 'Meningkatkan kemandirian, tanggung jawab, serta kedisiplinan anggota-mahasiswi PUB.'],
        [2, 'Menciptakan suasana yang santai sehingga tercipta rasa aman dan nyaman bagi anggota-mahasiswi PUB.'],
    ]

    for dapil in daftar_dapil:
        Dapil = apps.get_model('pemilu', 'Dapil')
        dapil_baru = Dapil(id=dapil[0], nama=dapil[1])
        dapil_baru.save()

    for angkatan in daftar_angkatan:
        Angkatan = apps.get_model('pemilu', 'Angkatan')
        angkatan_baru = Angkatan(nomor=angkatan[0], nama=angkatan[1])
        angkatan_baru.save()

    for anggota in daftar_anggota:
        Anggota = apps.get_model('pemilu', 'Anggota')
        anggota_baru = Anggota(nim=anggota[0], nama=anggota[1], dapil=Dapil.objects.get(id=anggota[2]))
        if (anggota[3]):
            anggota_baru.angkatan = Angkatan.objects.get(nomor=anggota[3])
        with transaction.atomic():
            anggota_baru.save()

    for jadwal in daftar_jadwal:
        Jadwal = apps.get_model('pemilu', 'Jadwal')
        jadwal_baru = Jadwal(tanggal_mulai=jadwal[0], tanggal_berakhir=jadwal[1], kegiatan=jadwal[2])
        with transaction.atomic():
            jadwal_baru.save()

    for kandidat in daftar_kandidat:
        Kandidat = apps.get_model('pemilu', 'Kandidat')
        kandidat_baru = Kandidat(nomor=kandidat[0], palsu=kandidat[1], anggota=Anggota.objects.get(nim=kandidat[2]), foto=kandidat[3], warna=kandidat[4])
        if kandidat[5]:
            kandidat_baru.visi = kandidat[5]
        kandidat_baru.save()
        kandidat_baru = Kandidat.objects.get(nomor=kandidat[0])

        for dapil in daftar_dapil:
            SuaraPerDapil = apps.get_model('pemilu', 'SuaraPerDapil')
            suara_per_dapil_baru = SuaraPerDapil(kandidat=kandidat_baru, dapil=Dapil.objects.get(id=dapil[0]))
            suara_per_dapil_baru.save()

        for angkatan in daftar_angkatan:
            SuaraPerAngkatan = apps.get_model('pemilu', 'SuaraPerAngkatan')
            suara_per_angkatan_baru = SuaraPerAngkatan(kandidat=kandidat_baru, angkatan=Angkatan.objects.get(nomor=angkatan[0]))
            suara_per_angkatan_baru.save()

    for misi in daftar_misi:
        Misi = apps.get_model('pemilu', 'Misi')
        misi_baru = Misi(kandidat=Kandidat.objects.get(nomor=misi[0]), isi=misi[1])
        misi_baru.save()

    User.objects.create_superuser('admin', None, '1234')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('nomor', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dapil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_berakhir', models.DateField(null=True)),
                ('kegiatan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('palsu', models.BooleanField(default=False)),
                ('nomor', models.IntegerField(primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=255, null=True)),
                ('warna', models.CharField(max_length=255)),
                ('visi', models.CharField(max_length=255)),
                ('suara', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuaraPerDapil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suara', models.IntegerField(default=0)),
                ('dapil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.dapil')),
                ('kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.kandidat')),
            ],
        ),
        migrations.CreateModel(
            name='SuaraPerAngkatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suara', models.IntegerField(default=0)),
                ('angkatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.angkatan')),
                ('kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.kandidat')),
            ],
        ),
        migrations.CreateModel(
            name='Misi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.CharField(max_length=255)),
                ('kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.kandidat')),
            ],
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('nim', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('hak_suara', models.IntegerField(default=1)),
                ('sudah_memilih', models.BooleanField(default=False)),
                ('foto', models.CharField(max_length=255, null=True)),
                ('akun', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('angkatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pemilu.angkatan')),
                ('dapil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.dapil')),
            ],
        ),
        migrations.AddField(
            model_name='kandidat',
            name='anggota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemilu.anggota'),
        ),
        migrations.RunPython(insert_data),
    ]
